out_dir: results/DGT
metric_best: rmse
metric_agg: argmin
wandb:
  use: True
  project: FreeSolv
dataset:
  format: PyG-MoleculeNet
  name: FreeSolv
  task: graph
  task_type: regression
  transductive: False
  split_mode: scaffold
  node_encoder: True
  node_encoder_name: LinearNode
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_shared: True
  edge_encoder_name: LinearEdge+RWSE
  edge_encoder_num_types: 3
  edge_encoder_bn: False
  # spd: True
  # spd_max_length: 6
  rings: True
  rings_max_length: 6
  rings_coalesce_edges: False
share:
  dim_in: 9
posenc_RWSE:
  enable: True
  enable_edges: True
  kernel:
    times_func: range(1,7)
  model: Linear
  dim_pe: 64
  raw_norm_type: None
train:
  mode: custom
  batch_size: 65
  eval_period: 1
  ckpt_period: 10
model:
  type: DGTModel
  loss_fun: mse
  edge_decoding: dot
  graph_pooling: add
gt:
  layer_type: None+DGT
  layers: 3
  n_heads: 16
  dim_hidden: 128  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.7
  layer_norm: False
  batch_norm: True
gnn:
  head: line_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 128  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: gelu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.00005
  max_epoch: 2000
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
